update@2025-09-10-23-10

diff --git a/luci-app-dockerman/root/etc/init.d/dockerman b/luci-app-dockerman/root/etc/init.d/dockerman
--- a/luci-app-dockerman/root/etc/init.d/dockerman
+++ b/luci-app-dockerman/root/etc/init.d/dockerman
@@ -93,9 +93,9 @@ handle_allowed_interface(){
 }
 
 start_service(){
-	delete_dockerman_chain
-	init_dockerman_chain
-	handle_allowed_interface
+	# delete_dockerman_chain
+	# init_dockerman_chain
+	# handle_allowed_interface
 	procd_open_instance
 	procd_set_param command /bin/sh -c '
 		docker events --filter event=start \
@@ -111,6 +111,15 @@ start_service(){
 	procd_close_instance
 }
 
+add_fw() {
+    if [ -z "$1" ]; then
+        echo "Error: Container name is required." >&2
+        echo "Usage: docker_fw_redirect <container_name>" >&2
+        return 1
+    fi
+    /usr/bin/docker-fw-redirect "$1"
+}
+
 stop_service(){
 	delete_dockerman_chain
 }
@@ -123,10 +132,6 @@ reload_service(){
 	start
 }
 
-boot(){
-	sleep 5s
-	start
-}
-
 extra_command "add_ports" "Add allowed ports based on the container ID(s)"
 extra_command "convert" "Convert Ac allowed container to AC allowed ports"
+extra_command "add_fw" "Configure Docker container port forwarding (NAT/firewall)"
